# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source "https://github.com/NavjotGT/SDK-PodSpecs.git"
target 'Github-Action' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Github-Action
#  pod 'SDK', :path => '../'
  pod 'SDK', '1.2'
end
