# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
   ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
end

platform :ios do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new iOS Beta Build to Crashlytics Beta"
  lane :beta do
  	# get_certificates
   #  get_provisioning_profile
    build_app(export_method: "development", scheme: "Github-Action")
    slack(message: 'Successfully distributed a new iOS beta build')
    # crashlytics
  end

  # error do |lane, exception|
  #   slack(
  #     message: exception.message,
  #     success: false)
  # end
end
