name: iOS

on:
  push:
    branches:
      - release-pipeline

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fastlane
      uses: maierj/fastlane-action@v1.4.0
      env:
        SLACK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
       lane: 'beta'